### ISSUE TITLE
Can't open edit screen in admin

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-content#29]
When browsing and clicking the file, for example settings_data.json in admin I should be able to modify it, however nothing happens (in our demo):

![image](https://user-images.githubusercontent.com/1566470/68166509-6aa46480-ff17-11e9-8ab6-a80784d104ca.png)

**Comment by trueboroda** [comment]
This problem is caused by the state of the data. It looks like it comes from the past. Export-import of content modules data solves the problem.  There is no such problem with newly created files.
The problem was related to the wrong mime type of files saved into Azure Blob Storage, the property "contentType" of the blob entity.

**Comment by trueboroda** [comment]
In https://admin-demo.virtocommerce.com/ such behavior is related to user permissions. For security purposes, the Admin user does not have the permissions to edit the content of any theme. 
![image](https://user-images.githubusercontent.com/13153256/69413386-c2b5d600-0d21-11ea-9ae1-7c6c3c2d670e.png)
